EXPERIMENT:
  NAME: ""
  TAG: "dkd_ours,vgg13,vgg8"
  PROJECT: "cub200_baselines"

DATASET:
  TYPE: "cub200"

DISTILLER:
  TYPE: "DKD_Ours"
  TEACHER: "vgg13"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.025
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
KD_Ours:
  GAMMA: 6.0
