EXPERIMENT:
  NAME: ""
  TAG: "rekd_ours,res32x4,mv2"
  PROJECT: "cub200_baselines"


DATASET:
  TYPE: "cub200"

DISTILLER:
  TYPE: "ReKD_Ours"
  TEACHER: "resnet32x4"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.025
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

